### ISSUE TITLE
Add link to Docker proxy configuration for CE

### ISSUE THREAD

**Issue by przmv** [tidalmigrations/tidalmigrations.github.io#70]
[Specifying Docker proxy](https://github.com/tidalmigrations/tidalmigrations.github.io/blob/master/pages/tidal%20tools/troubleshooting.md#specifying-docker-proxy) section of the Troubleshooting Guide currently has a link to Windows specific proxy configuration instructions.

We should either add link to Docker for Linux proxy configuration page or use different sections — Windows-specific and Linux-specific when describing Docker proxy configuration.

WDYT @pnr?

**Comment by prees1** [comment]
💯 
I think a quick solution is adding a linux configuration link to that section.

Would the two sections be 'troubleshooting docker on X' one for wind and one for 'nix? I think that would  make sense if we have several issues that are OS specific in their cause or solution.

**Comment by prees1** [comment]
@pshevtsov Is this the link we should include for configuring docker on Linux to use a proxy? - https://docs.docker.com/network/proxy/

**Comment by pshevtsov** [comment]
Yes, looks like it's the correct link. My bad I hadn't provided the correct links beforehand.
