### ISSUE TITLE
Inconsistent word delimiters in URLs

### ISSUE THREAD

**Issue by pshevtsov** [tidalmigrations/tidalmigrations.github.io#82]
We have three different word delimiters in out URLs, for example:

* `/import-from-excel.html`
* `/source_code_insights.html`
* `/createinterviewquestions.html`

My vote is for hyphens (`-`) as word delimiters. Google also recommends to use hyphens:

> Consider using punctuation in your URLs. The URL **http://www.example.com/green-dress.html** is much more useful to us than **http://www.example.com/greendress.html**. We recommend that you use hyphens (`-`) instead of underscores (`_`) in your URLs.
>
> — [Keep a simple URL structure](https://support.google.com/webmasters/answer/76329?hl=en)

**Comment by prees1** [comment]
Yea I agree let's simplify - hyphens are good with me. Before any existing ones are changed, we will have make sure any references elsewhere are updated as well.

**Comment by justinbarclay** [comment]
Agreed
